
export enum MessageType {
    SETUP_COMMUNICATION,
    COMMUNICATION_ESTABLISHED,
    COMMAND_INPUT_FILLER,
    COMMAND_NO_COMPONENT,
    COMMAND_YOUTUBE_VIDEO_SELECTION_ON_DESKTOP,
    COMMAND_PAUSE_OR_PLAY_YOUTUBE_VIDEO,
    COMMAND_START_NEXT_YOUTUBE_VIDEO,
    COMMAND_MUTE_YOUTUBE_VIDEO,
    COMMAND_UNMUTE_YOUTUBE_VIDEO,
    COMMAND_CHANGE_VOLUME_ON_YOUTUBE_VIDEO,
    COMMAND_ACTIVATE_YOUTUBE_CINEMA_MODE,
    COMMAND_DEACTIVATE_YOUTUBE_CINEMA_MODE,
    COMMAND_ACTIVATE_YOUTUBE_FULLSCREEN,
    COMMAND_DEACTIVATE_YOUTUBE_FULLSCREEN,
    COMMAND_ACTIVATE_YOUTUBE_SEARCH,
    COMMAND_CALL
}

export interface Message {
    message?: any,
    type: MessageType
}